config/routes.rb
Rails.application.routes.draw do
	root 'users#index'
  
	resources :users

	resources :blog_posts

  get '/index', to: 'static_pages#index'

  # get '/post', to: 'static_pages#post'

  get '/about', to: 'static_pages#about'

  get '/contact', to: 'static_pages#contact'

  # get '/userlist', to: 'users#index'

  # root 'static_pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
	belongs_to :user
	
	validates :title, length: {maximum:50}
	validates :title, presence: true

	validates :user_id, presence: true
	validates :content, presence: true
	
end

app/models/user.rb
class User < ApplicationRecord
	has_many :blog_post, dependent: :destroy
	
	validates :name, length: {maximum:45}
	validates :name, presence: true

	validates :email, length: {maximum:45}
	validates_format_of :email,:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
	validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
	def index
		@blog_posts = BlogPost.all
	end

	def new
		@blog_post = BlogPost.new
	end
	
	def create
		@blog_post = BlogPost.new(blog_post_params)
		if @blog_post.valid?
			@blog_post.save
			redirect_to @blog_post
		else
			render 'new'
		end
	end

	def edit
		@blog_post = BlogPost.find(params[:id])
	end

	def update
		@blog_post = BlogPost.find(params[:id])
		@blog_post.update_attributes(blog_post_params)
		if @blog_post.valid?
			@blog_post.save
			redirect_to @blog_post
		else
			render 'edit'
		end
	end
	
	def destroy
		BlogPost.find(params[:id]).destroy
    flash[:success] = "BlogPost deleted"
    redirect_to blog_posts_path
	end

	def show
		@blog_post = BlogPost.find(params[:id])
		@user = @blog_post.user
		# raise 'a'
	end

	private

	def blog_post_params
		params.require(:blog_post).permit(:title, :summary, :content, :user_id, :title_image_url)
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def post
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index		
		@users = User.all
	end

	def show	
		@user = User.find(params[:id])
	end

	def new
		@user = User.new	
	end

	def create
		@user = User.new(user_params)
		if @user.valid?
			@user.save
			redirect_to @user
		else
			render 'new'  
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		@user.update_attributes(user_params)
		if @user.valid?
			@user.save
			redirect_to @user
		else
			render 'edit'
		end
	end

	def destroy
		User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_path
	end

	private

	def user_params
		params.require(:user).permit(:name, :email)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/blog_posts/_form.html.erb
<br />
<%= form_for(@blog_post) do |f| %>
  <div class="row control-group">
    <div class="form-group col-xs-12 floating-label-form-group controls">
      <p><%= f.text_field :title, placeholder: "Title", size: "50" %></p>
      <p style="color:red;"><%= @blog_post.errors.full_messages_for(:title).join(", ") if @blog_post.errors.include?(:title)%></p>
      <p><%= f.text_area :summary, placeholder: "Summary", size: "50x2" %></p>
      <p><%= f.text_area :content, placeholder: "Content", size: "50x5" %></p>
      <p style="color:red;"><%= @blog_post.errors.full_messages_for(:content).join(", ") if @blog_post.errors.include?(:content)%></p>
      <p>
        User:
        <%= f.select(:user_id) do %>
          <% User.all.each do |user| %>
            <%= content_tag(:option, user.name, value: user.id) %>
          <% end %>
        <% end %>
      </p>
      <p><%= f.text_field :title_image_url, placeholder: "Image URL" %></p>
      <p style="color:red;"><%= f.submit "Post", class:"btn btn-default" %></p>
    </div>
  </div>
<% end %>

app/views/blog_posts/edit.html.erb
<header class="intro-header" style="background-image: url('/assets/post-bg.jpg')">
  <div class="container">
      <div class="row">
          <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
              <div class="page-heading">
                  <h1>User</h1>
                  <hr class="small">
                  <span class="subheading">Clean Blog</span>
              </div>
          </div>
      </div>
  </div>
</header>

<!-- Main Content -->
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">

        Add New Post

        <br />

        <%= render 'form' %>

        </div>
    </div>
</div>

app/views/blog_posts/index.html.erb
<header class="intro-header" style="background-image: url('/assets/post-bg.jpg')">
  <div class="container">
      <div class="row">
          <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
              <div class="page-heading">
                  <h1>Clean Blog</h1>
                  <hr class="small">
                  <span class="subheading">List of Posts</span>
              </div>
          </div>
      </div>
  </div>
</header>

<div class="container">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
          <b style="color:red;"><%= link_to 'Create New Post', new_blog_post_path %></b>

          <% @blog_posts.each do |blog_post| %>
            <div class="post-preview">

              <%= link_to(blog_post_path(blog_post)) do %>
                <h2 class="post-title">
                  <%= blog_post.title %>
                </h2>
                
                <h3 class="post-subtitle">
                 <%= blog_post.summary %>
                </h3>                
              <% end %>              

              

              <p class="post-meta">Posted by <%= blog_post.user.try(:name) %> on <%= blog_post.created_at.localtime.strftime('%c') %></p>
            </div>
          <% end %>
        </div>


    </div>
</div>

app/views/blog_posts/new.html.erb
<header class="intro-header" style="background-image: url('/assets/post-bg.jpg')">
  <div class="container">
      <div class="row">
          <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
              <div class="page-heading">
                  <h1>Clean Blog</h1>
                  <hr class="small">
                  <span class="subheading">Create New Post</span>
              </div>
          </div>
      </div>
  </div>
</header>

<!-- Main Content -->
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">

        <b>You can add new post here.</b>

        <br />

        <%= render 'form' %>

        </div>
    </div>
</div>

app/views/blog_posts/show.html.erb
<header class="intro-header" style="background-image: url( <%= @blog_post.title_image_url %>)">
  <div class="container">
      <div class="row">
          <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
              <div class="page-heading">
                <h1><%= @blog_post.title %></h1>
                <hr class="small">
                <span class="subheading"><%= @blog_post.summary %></span>
                  <span class="meta">
                    Posted by <a href="#"><%= @user.name %></a> 
                    on <%= @blog_post.created_at.strftime('%c') %>
                  </span>
              </div>
          </div>
      </div>
  </div>
</header>


<!-- Main Content -->
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">

        <br />
        <%= link_to 'Edit', edit_blog_post_path(@blog_post) %>
        <%= link_to "Delete", @blog_post, method: :delete,
                                  data: { confirm: "You sure?" } %>
        <p><%= @blog_post.content %></p>

        <br />
          <%= link_to 'Back to Blogposts', blog_posts_path %>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CleanBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>    
    
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
  </head>

  <body>


    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="#">Add New Post</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="/index">Home</a>
                    </li>
                    <li>
                        <a href="/about">About</a>
                    </li>
                    <li>
                        <%= link_to 'BlogPosts', blog_posts_path %>
                    </li>
                    <li>
                        <!-- <a href="/userlist">Users</a> -->
                        <%= link_to 'Users', users_path %>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

  	<%= yield %>   

    <hr>

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; Your Website 2016</p>
                </div>
            </div>
        </div>
    </footer>

  </body>
  <%= javascript_include_tag 'application' %>
</html>

app/views/static_pages/about.html.erb
    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url('/assets/about-bg.jpg')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="page-heading">
                        <h1>About Me</h1>
                        <hr class="small">
                        <span class="subheading">This is what I do.</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum molestiae debitis nobis, quod sapiente qui voluptatum, placeat magni repudiandae accusantium fugit quas labore non rerum possimus, corrupti enim modi! Et.</p>
            </div>
        </div>
    </div>

app/views/static_pages/contact.html.erb
    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url('/assets/contact-bg.jpg')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="page-heading">
                        <h1>Contact Me</h1>
                        <hr class="small">
                        <span class="subheading">Have questions? I have answers (maybe).</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <p>Want to get in touch with me? Fill out the form below to send me a message and I will try to get back to you within 24 hours!</p>
                <!-- Contact Form - Enter your email address on line 19 of the mail/contact_me.php file to make this form work. -->
                <!-- WARNING: Some web hosts do not allow emails to be sent through forms to common mail hosts like Gmail or Yahoo. It's recommended that you use a private domain email address! -->
                <!-- NOTE: To use the contact form, your site must be on a live web host with PHP! The form will not work locally! -->
                <form name="sentMessage" id="contactForm" novalidate>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Name</label>
                            <input type="text" class="form-control" placeholder="Name" id="name" required data-validation-required-message="Please enter your name.">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Email Address</label>
                            <input type="email" class="form-control" placeholder="Email Address" id="email" required data-validation-required-message="Please enter your email address.">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Phone Number</label>
                            <input type="tel" class="form-control" placeholder="Phone Number" id="phone" required data-validation-required-message="Please enter your phone number.">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Message</label>
                            <textarea rows="5" class="form-control" placeholder="Message" id="message" required data-validation-required-message="Please enter a message."></textarea>
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <br>
                    <div id="success"></div>
                    <div class="row">
                        <div class="form-group col-xs-12">
                            <button type="submit" class="btn btn-default">Send</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

app/views/static_pages/index.html.erb
    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url('/assets/home-bg.jpg')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>Clean Blog</h1>
                        <hr class="small">
                        <span class="subheading">A Clean Blog Theme by Start Bootstrap</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="post-preview">
                    <a href="post.html">
                        <h2 class="post-title">
                            Man must explore, and this is exploration at its greatest
                        </h2>
                        <h3 class="post-subtitle">
                            Problems look mighty small from 150 miles up
                        </h3>
                    </a>
                    <p class="post-meta">Posted by <a href="#">Start Bootstrap</a> on September 24, 2014</p>
                </div>
                <hr>
                <div class="post-preview">
                    <a href="post.html">
                        <h2 class="post-title">
                            I believe every human has a finite number of heartbeats. I don't intend to waste any of mine.
                        </h2>
                    </a>
                    <p class="post-meta">Posted by <a href="#">Start Bootstrap</a> on September 18, 2014</p>
                </div>
                <hr>
                <div class="post-preview">
                    <a href="post.html">
                        <h2 class="post-title">
                            Science has not yet mastered prophecy
                        </h2>
                        <h3 class="post-subtitle">
                            We predict too much for the next year and yet far too little for the next ten.
                        </h3>
                    </a>
                    <p class="post-meta">Posted by <a href="#">Start Bootstrap</a> on August 24, 2014</p>
                </div>
                <hr>
                <div class="post-preview">
                    <a href="post.html">
                        <h2 class="post-title">
                            Failure is not an option
                        </h2>
                        <h3 class="post-subtitle">
                            Many say exploration is part of our destiny, but it’s actually our duty to future generations.
                        </h3>
                    </a>
                    <p class="post-meta">Posted by <a href="#">Start Bootstrap</a> on July 8, 2014</p>
                </div>
                <hr>
                <!-- Pager -->
                <ul class="pager">
                    <li class="next">
                        <a href="#">Older Posts &rarr;</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

app/views/static_pages/post.html.erb
    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url('/assets/post-bg.jpg')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="post-heading">
                        <h1>Man must explore, and this is exploration at its greatest</h1>
                        <h2 class="subheading">Problems look mighty small from 150 miles up</h2>
                        <span class="meta">Posted by <a href="#">Start Bootstrap</a> on August 24, 2014</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Post Content -->
    <article>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <p>Never in all their history have men been able truly to conceive of the world as one: a single sphere, a globe, having the qualities of a globe, a round earth in which all the directions eventually meet, in which there is no center because every point, or none, is center — an equal earth which all men occupy as equals. The airman's earth, if free men make it, will be truly round: a globe in practice, not in theory.</p>

                    <p>Science cuts two ways, of course; its products can be used for both good and evil. But there's no turning back from science. The early warnings about technological dangers also come from science.</p>

                    <p>What was most significant about the lunar voyage was not that man set foot on the Moon but that they set eye on the earth.</p>

                    <p>A Chinese tale tells of some men sent to harm a young girl who, upon seeing her beauty, become her protectors rather than her violators. That's how I felt seeing the Earth for the first time. I could not help but love and cherish her.</p>

                    <p>For those who have seen the Earth from space, and for the hundreds and perhaps thousands more who will, the experience most certainly changes your perspective. The things that we share in our world are far more valuable than those which divide us.</p>

                    <h2 class="section-heading">The Final Frontier</h2>

                    <p>There can be no thought of finishing for ‘aiming for the stars.’ Both figuratively and literally, it is a task to occupy the generations. And no matter how much progress one makes, there is always the thrill of just beginning.</p>

                    <p>There can be no thought of finishing for ‘aiming for the stars.’ Both figuratively and literally, it is a task to occupy the generations. And no matter how much progress one makes, there is always the thrill of just beginning.</p>

                    <blockquote>The dreams of yesterday are the hopes of today and the reality of tomorrow. Science has not yet mastered prophecy. We predict too much for the next year and yet far too little for the next ten.</blockquote>

                    <p>Spaceflights cannot be stopped. This is not the work of any one man or even a group of men. It is a historical process which mankind is carrying out in accordance with the natural laws of human development.</p>

                    <h2 class="section-heading">Reaching for the Stars</h2>

                    <p>As we got further and further away, it [the Earth] diminished in size. Finally it shrank to the size of a marble, the most beautiful you can imagine. That beautiful, warm, living object looked so fragile, so delicate, that if you touched it with a finger it would crumble and fall apart. Seeing this has to change a man.</p>

                    <a href="#">
                        <%=image_tag("post-sample-image.jpg")%>
                    </a>
                    <span class="caption text-muted">To go places and do things that have never been done before – that’s what living is all about.</span>

                    <p>Space, the final frontier. These are the voyages of the Starship Enterprise. Its five-year mission: to explore strange new worlds, to seek out new life and new civilizations, to boldly go where no man has gone before.</p>

                    <p>As I stand out here in the wonders of the unknown at Hadley, I sort of realize there’s a fundamental truth to our nature, Man must explore, and this is exploration at its greatest.</p>

                    <p>Placeholder text by <a href="http://spaceipsum.com/">Space Ipsum</a>. Photographs by <a href="https://www.flickr.com/photos/nasacommons/">NASA on The Commons</a>.</p>
                </div>
            </div>
        </div>
    </article>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <div class="row control-group">
    <div class="form-group col-xs-12 floating-label-form-group controls">
        <p><%= f.text_field :name, placeholder: "Name" %></p>
        <p style="color:red;"><%= @user.errors.full_messages_for(:name).join(", ") if @user.errors.include?(:name)%></p>
        <p><%= f.text_field :email, placeholder: "Email" %></p>
        <p style="color:red;"><%= @user.errors.full_messages_for(:email).join(", ") if @user.errors.include?(:email)%></p>
        <p><%= f.submit "Submit", class:"btn btn-default" %></p>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<header class="intro-header" style="background-image: url('/assets/about-bg.jpg')">
  <div class="container">
      <div class="row">
          <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
              <div class="page-heading">
                  <h1>Clean Blog</h1>
                  <hr class="small">
                  <span class="subheading">Edit User</span>
              </div>
          </div>
      </div>
  </div>
</header>

<!-- Main Content -->
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">

        <h1>Edit User</h1>
        <br />

        <%= render 'form' %>

        </div>
    </div>
</div>

app/views/users/index.html.erb
<header class="intro-header" style="background-image: url('/assets/about-bg.jpg')">
  <div class="container">
      <div class="row">
          <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
              <div class="page-heading">
                  <h1>Clean Blog</h1>
                  <hr class="small">
                  <span class="subheading">List of Users</span>
              </div>
          </div>
      </div>
  </div>
</header>



<!-- Main Content -->
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
          <b style="color:red;"><%= link_to 'Create New User', new_user_path %></b>

          <table width="100%">
            <tr style="background-color: gray;
            color:white;">
              <td>ID</td>
              <td width="20%">Name</td>
              <td width="20%">Email</td>
              <td>Created at</td>
              <td>Updated at</td>
              <td colspan="2" width="20%">Action</td>
            </tr>

            <% @users.each do |user| %>
              <tr>
                <td><%= user.id %></td>              
                <td><%= user.name %></td>
                <td><%= user.email %></td>
                <td><%= user.created_at.localtime.strftime('%c') %></td>
                <td><%= user.updated_at.localtime.strftime('%c') %></td>
                <td><%= link_to 'Edit',edit_user_path(user) %></td>
                <td>
                  <%= link_to "Delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
                </td>                
              </tr>
            <% end %>
          </table>
        </div>
    </div>
</div>

app/views/users/new.html.erb
<header class="intro-header" style="background-image: url('/assets/about-bg.jpg')">
  <div class="container">
      <div class="row">
          <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
              <div class="page-heading">
                  <h1>Clean Blog</h1>
                  <hr class="small">
                  <span class="subheading">Create New User</span>
              </div>
          </div>
      </div>
  </div>
</header>
<!-- Main Content -->
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">

        <b>You can add new user here.</b>

        <br />

        <%= render 'form' %>

        </div>
    </div>
</div>

app/views/users/show.html.erb
<header class="intro-header" style="background-image: url('/assets/post-bg.jpg')">
  <div class="container">
      <div class="row">
          <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
              <div class="page-heading">
                  <h1>User</h1>
                  <hr class="small">
                  <span class="subheading">Showing User</span>
              </div>
          </div>
      </div>
  </div>
</header>


<!-- Main Content -->
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">

        <table border="1" width="50%">
        	<tr>
        		<td width="50%">ID</td>
        		<td width="50%"><%= @user.id %></td>
        	</tr>
        	<tr>
        		<td>Name</td>
        		<td><%= @user.name %></td>
        	</tr>
        	<tr>
        		<td>Email</td>
        		<td><%= @user.email %></td>
        	</tr>
        </table>

        	<%= link_to 'Back to Users', users_path %>

        </div>
    </div>
</div>